version: "2"         # required to adjust maintainability checks
checks:
  argument-count:
    config:
      threshold: 7
  return-statements:
    config:
      threshold: 30
  file-lines:
    config:
      threshold: 250
  method-lines:
    config:
      threshold: 250